import './style.css'
import { jsPDF } from 'jspdf'
import { PDFDocument, degrees } from 'pdf-lib'
import JSZip from 'jszip'
import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf.mjs'

type Tool = { name: string; category: string; description: string; icon: string; color: string; popular?: boolean }

const allTools: Tool[] = [
  { name: 'Merge PDF', category: 'Organize', description: 'Combine multiple files into one clean document.', icon: '+', color: 'coral', popular: true },
  { name: 'Split PDF', category: 'Organize', description: 'Separate pages or ranges into new PDFs.', icon: '/', color: 'coral' },
  { name: 'Remove pages', category: 'Organize', description: 'Delete unwanted pages in seconds.', icon: 'x', color: 'coral' },
  { name: 'Extract pages', category: 'Organize', description: 'Pull out the pages you need to share.', icon: '->', color: 'coral' },
  { name: 'Organize PDF', category: 'Organize', description: 'Reorder, rotate, and manage every page.', icon: '≡', color: 'coral' },
  { name: 'Scan to PDF', category: 'Organize', description: 'Turn scans and photos into searchable PDFs.', icon: '[]', color: 'coral' },
  { name: 'Compress PDF', category: 'Optimize', description: 'Shrink file size while keeping it crisp.', icon: '◆', color: 'green', popular: true },
  { name: 'Repair PDF', category: 'Optimize', description: 'Recover content from damaged documents.', icon: '✓', color: 'green' },
  { name: 'OCR PDF', category: 'Optimize', description: 'Make scanned text searchable and editable.', icon: 'OCR', color: 'green' },
  { name: 'JPG to PDF', category: 'Convert to PDF', description: 'Create a PDF from your images.', icon: 'JPG', color: 'yellow' },
  { name: 'WORD to PDF', category: 'Convert to PDF', description: 'Convert Word documents with the layout intact.', icon: 'W', color: 'blue' },
  { name: 'POWERPOINT to PDF', category: 'Convert to PDF', description: 'Share presentations as polished PDFs.', icon: 'P', color: 'orange' },
  { name: 'EXCEL to PDF', category: 'Convert to PDF', description: 'Export spreadsheets for easy sharing.', icon: 'X', color: 'green' },
  { name: 'HTML to PDF', category: 'Convert to PDF', description: 'Save web pages as print-ready PDFs.', icon: '◎', color: 'yellow' },
  { name: 'PDF to JPG', category: 'Convert from PDF', description: 'Turn pages into high-quality images.', icon: 'JPG', color: 'yellow' },
  { name: 'PDF to WORD', category: 'Convert from PDF', description: 'Edit PDF content in Microsoft Word.', icon: 'W', color: 'blue', popular: true },
  { name: 'PDF to POWERPOINT', category: 'Convert from PDF', description: 'Transform pages into editable slides.', icon: 'P', color: 'orange' },
  { name: 'PDF to EXCEL', category: 'Convert from PDF', description: 'Extract tables into usable spreadsheets.', icon: 'X', color: 'green' },
  { name: 'PDF to PDF/A', category: 'Convert from PDF', description: 'Archive documents for long-term access.', icon: 'A', color: 'blue' },
  { name: 'Rotate PDF', category: 'Edit PDF', description: 'Fix page orientation in a few clicks.', icon: '↻', color: 'plum' },
  { name: 'Add page numbers', category: 'Edit PDF', description: 'Number pages with flexible placement.', icon: '12', color: 'plum' },
  { name: 'Add watermark', category: 'Edit PDF', description: 'Stamp documents with your brand or status.', icon: '↓', color: 'plum' },
  { name: 'Crop PDF', category: 'Edit PDF', description: 'Trim margins and frame your content.', icon: '⌗', color: 'plum' },
  { name: 'Edit PDF', category: 'Edit PDF', description: 'Add text, images, and annotations.', icon: '✎', color: 'plum', popular: true },
  { name: 'PDF Forms', category: 'Edit PDF', description: 'Create and fill interactive form fields.', icon: '▣', color: 'plum' },
  { name: 'Unlock PDF', category: 'PDF Security', description: 'Remove passwords when you have permission.', icon: '▣', color: 'navy' },
  { name: 'Protect PDF', category: 'PDF Security', description: 'Secure documents with a strong password.', icon: '◇', color: 'navy' },
  { name: 'Sign PDF', category: 'PDF Security', description: 'Add your signature to important files.', icon: '✒', color: 'navy' },
  { name: 'Redact PDF', category: 'PDF Security', description: 'Permanently hide sensitive information.', icon: '—', color: 'navy' },
  { name: 'Compare PDF', category: 'PDF Security', description: 'Spot every difference between two versions.', icon: '▤', color: 'navy' },
  { name: 'AI Summarizer', category: 'PDF Intelligence', description: 'Get the key ideas from any document.', icon: '✦', color: 'violet', popular: true },
  { name: 'Translate PDF', category: 'PDF Intelligence', description: 'Translate documents without losing structure.', icon: '文', color: 'violet' },
  { name: 'PDF to Markdown', category: 'PDF Intelligence', description: 'Turn PDFs into clean, structured Markdown.', icon: '{}', color: 'violet' },
]

const workingToolNames = new Set(['Merge PDF', 'Split PDF', 'Remove pages', 'Extract pages', 'Organize PDF', 'Compress PDF', 'Repair PDF', 'JPG to PDF', 'PDF to JPG', 'Rotate PDF', 'Add page numbers', 'Add watermark', 'Crop PDF', 'PDF Forms', 'Compare PDF', 'PDF to Markdown'])
const tools = allTools.filter((tool) => workingToolNames.has(tool.name))

const categories = ['All tools', ...Array.from(new Set(tools.map((tool) => tool.category)))]
let activeCategory = 'All tools'
let query = ''

const app = document.querySelector<HTMLDivElement>('#app')!
app.innerHTML = `
  <header class="topbar"><a class="brand" href="#top" aria-label="PDF Flex home"><span class="brand-mark">P</span><span>PDF<span class="brand-accent">flex</span></span></a><nav class="main-nav" aria-label="Primary navigation"><a class="active" href="#tools">All tools</a><a href="#recent">Recent</a><a href="#about">About</a></nav><div class="top-actions"><button class="icon-button" aria-label="Toggle theme">◐</button><button class="outline-button">Sign in</button><button class="solid-button small">Get started <span>↗</span></button></div><button class="menu-button" aria-label="Open menu">☰</button></header>
  <main id="top"><section class="hero"><div class="hero-copy"><p class="eyebrow"><span></span> YOUR EVERYDAY PDF WORKSPACE</p><h1>Make PDFs work<br><em>for you.</em></h1><p class="hero-text">Everything you need to organize, convert, edit, and understand your documents. Fast, private, and beautifully simple.</p><div class="hero-buttons"><button class="solid-button" data-tool="Merge PDF">Start with a file <span>↗</span></button><a class="text-button" href="#tools">Explore all tools <span>↓</span></a></div></div><div class="hero-art" aria-hidden="true"><div class="paper paper-back"></div><div class="paper paper-main"><span class="paper-label">PDF</span><span class="paper-line wide"></span><span class="paper-line"></span><span class="paper-line short"></span><span class="paper-shape"></span></div><div class="floating-note note-one">✦ <b>${tools.length} tools</b><small>that work today</small></div><div class="floating-note note-two"><span class="green-dot"></span> Private by design</div></div></section>
  <section class="workspace" id="tools"><div class="workspace-head"><div><p class="eyebrow">THE TOOLBOX</p><h2>What are you working on?</h2></div><label class="search"><span>⌕</span><input id="search" type="search" placeholder="Search tools..." aria-label="Search tools"></label></div><div class="category-tabs" role="tablist">${categories.map((category, index) => `<button class="category-tab ${index === 0 ? 'selected' : ''}" data-category="${category}" role="tab">${category}</button>`).join('')}</div><div class="tool-grid" id="tool-grid"></div></section>
  <section class="upload-band" id="recent"><div class="upload-copy"><p class="eyebrow">QUICK START</p><h2>Drop a file.<br><em>Get to work.</em></h2><p>Pick any tool above or drop your PDF here to see what you can do next.</p></div><label class="dropzone" id="dropzone"><input id="file-input" type="file" accept="application/pdf,image/*,.doc,.docx,.xls,.xlsx,.ppt,.pptx" multiple><span class="upload-icon">↑</span><strong>Drop files here</strong><span>or <u>browse your device</u></span><small>PDF, DOCX, XLSX, PPTX, JPG up to 100 MB</small></label></section><section class="trust-row" id="about"><span>Used by people who care about their documents</span><div><b>NO ACCOUNT NEEDED</b><b>FILES AUTO-DELETED</b><b>PRIVATE &amp; SECURE</b></div></section></main>
  <footer><a class="brand" href="#top"><span class="brand-mark">P</span><span>PDF<span class="brand-accent">flex</span></span></a><span>Simple tools for important work.</span><span class="footer-right">Made for the way you work with PDFs.</span></footer><nav class="floating-nav" aria-label="Quick navigation"><a class="floating-nav-item active" href="#top" aria-label="Home"><span>⌂</span><small>Home</small></a><a class="floating-nav-item" href="#tools" aria-label="Tools"><span>✦</span><small>Tools</small></a><a class="floating-nav-item floating-nav-main" href="#recent" aria-label="Upload a file"><span>↑</span><small>Upload</small></a><a class="floating-nav-item" href="#recent" aria-label="Recent files"><span>◷</span><small>Recent</small></a><a class="floating-nav-item" href="#about" aria-label="About PDFflex"><span>i</span><small>About</small></a></nav><div class="modal-backdrop" id="modal" hidden><div class="modal" role="dialog" aria-modal="true"><button class="modal-close" aria-label="Close">×</button><span class="modal-icon" id="modal-icon">+</span><p class="eyebrow">READY WHEN YOU ARE</p><h2 id="modal-title">Merge PDF</h2><p id="modal-description"></p><div class="modal-files" id="modal-files"></div><label class="modal-upload"><input id="modal-file" type="file" multiple accept="application/pdf,image/*,.doc,.docx,.xls,.xlsx,.ppt,.pptx"><span>↑</span> Choose files to begin</label><button class="convert-button" id="convert-button" disabled>Convert to PDF <span>↗</span></button><div class="progress-area" id="progress-area" hidden><div class="progress-heading"><span id="progress-label">Preparing files</span><b id="progress-value">0%</b></div><div class="progress-track"><span id="progress-bar"></span></div></div><button class="download-button" id="download-button" hidden>Download converted file <span>↓</span></button><p class="conversion-status" id="conversion-status" role="status"></p><p class="modal-footnote">Your files stay private and are deleted automatically.</p></div></div>`

const grid = document.querySelector<HTMLDivElement>('#tool-grid')!
const renderTools = () => { const visible = tools.filter((tool) => (activeCategory === 'All tools' || tool.category === activeCategory) && tool.name.toLowerCase().includes(query.toLowerCase())); grid.innerHTML = visible.length ? visible.map((tool) => `<button class="tool-card" data-tool="${tool.name}"><span class="tool-icon ${tool.color}">${tool.icon}</span><span class="tool-info"><strong>${tool.name}</strong><small>${tool.description}</small></span>${tool.popular ? '<span class="popular">Popular</span>' : ''}<span class="card-arrow">↗</span></button>`).join('') : '<div class="empty-state">No tools match that search. Try another phrase.</div>' }
renderTools()
const modal = document.querySelector<HTMLDivElement>('#modal')!
let selectedFiles: File[] = []
let selectedTool = tools[0]
const modalFiles = document.querySelector<HTMLDivElement>('#modal-files')!
const conversionStatus = document.querySelector<HTMLParagraphElement>('#conversion-status')!
const convertButton = document.querySelector<HTMLButtonElement>('#convert-button')!
const modalFileInput = document.querySelector<HTMLInputElement>('#modal-file')!
const progressArea = document.querySelector<HTMLDivElement>('#progress-area')!
const progressBar = document.querySelector<HTMLSpanElement>('#progress-bar')!
const progressValue = document.querySelector<HTMLElement>('#progress-value')!
const progressLabel = document.querySelector<HTMLElement>('#progress-label')!
const downloadButton = document.querySelector<HTMLButtonElement>('#download-button')!
let conversionTimer: number | undefined
let outputUrl = ''
let conversionRun = 0
const browserSupportedTools = new Set(['JPG to PDF'])
const browserPdfTools = new Set(['Merge PDF', 'Split PDF', 'Remove pages', 'Extract pages', 'Rotate PDF'])
const browserImageTools = new Set(['PDF to JPG'])
const formatBytes = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(1)} MB`
const readAsDataUrl = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file) })
const pdfBlob = async (bytes: Uint8Array) => new Blob([bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength) as ArrayBuffer], { type: 'application/pdf' })
const createPdfFromImages = async (files: File[]) => { const pdf = new jsPDF({ unit: 'pt', format: 'a4', compress: true }); const pageWidth = pdf.internal.pageSize.getWidth(); const pageHeight = pdf.internal.pageSize.getHeight(); for (const [index, file] of files.entries()) { const dataUrl = await readAsDataUrl(file); const image = await new Promise<HTMLImageElement>((resolve, reject) => { const element = new Image(); element.onload = () => resolve(element); element.onerror = reject; element.src = dataUrl }); if (index > 0) pdf.addPage(); const scale = Math.min((pageWidth - 48) / image.naturalWidth, (pageHeight - 48) / image.naturalHeight); const width = image.naturalWidth * scale; const height = image.naturalHeight * scale; pdf.addImage(dataUrl, file.type === 'image/png' ? 'PNG' : 'JPEG', (pageWidth - width) / 2, (pageHeight - height) / 2, width, height); } return pdf.output('blob') }
const createJpgFromPdf = async (file: File) => { const pdfDocument = await pdfjsLib.getDocument({ data: await file.arrayBuffer() }).promise; const zip = new JSZip(); for (let pageNumber = 1; pageNumber <= pdfDocument.numPages; pageNumber += 1) { const page = await pdfDocument.getPage(pageNumber); const viewport = page.getViewport({ scale: 1.5 }); const canvas = document.createElement('canvas'); canvas.width = viewport.width; canvas.height = viewport.height; await page.render({ canvas, canvasContext: canvas.getContext('2d')!, viewport }).promise; const blob = await new Promise<Blob>((resolve, reject) => canvas.toBlob((value) => value ? resolve(value) : reject(new Error('Could not render page')), 'image/jpeg', .92)); zip.file(`page-${pageNumber}.jpg`, blob) } return zip.generateAsync({ type: 'blob' }) }
const createPdfOutput = async (toolName: string, files: File[]) => { if (toolName === 'JPG to PDF') return { blob: await createPdfFromImages(files), extension: 'pdf', name: 'jpg-to-pdf' }; if (toolName === 'PDF to JPG') return { blob: await createJpgFromPdf(files[0]), extension: 'zip', name: 'pdf-to-jpg' }; const sourceBytes = await files[0].arrayBuffer(); const source = await PDFDocument.load(sourceBytes); if (toolName === 'Merge PDF') { const merged = await PDFDocument.create(); for (const file of files) { const document = await PDFDocument.load(await file.arrayBuffer()); const pages = await merged.copyPages(document, document.getPageIndices()); pages.forEach((page) => merged.addPage(page)) } return { blob: await pdfBlob(await merged.save()), extension: 'pdf', name: 'merged' } } if (toolName === 'Rotate PDF') { source.getPages().forEach((page) => page.setRotation(degrees((page.getRotation().angle + 90) % 360))); return { blob: await pdfBlob(await source.save()), extension: 'pdf', name: 'rotated' } } if (toolName === 'Remove pages' || toolName === 'Extract pages') { const output = await PDFDocument.create(); const indexes = toolName === 'Remove pages' ? source.getPageIndices().slice(1) : source.getPageIndices().slice(0, 1); const pages = await output.copyPages(source, indexes); pages.forEach((page) => output.addPage(page)); return { blob: await pdfBlob(await output.save()), extension: 'pdf', name: toolName.toLowerCase().replaceAll(' ', '-') } } if (toolName === 'Split PDF') { const zip = new JSZip(); for (const [index] of source.getPages().entries()) { const output = await PDFDocument.create(); const [page] = await output.copyPages(source, [index]); output.addPage(page); zip.file(`page-${index + 1}.pdf`, await output.save()) } return { blob: await zip.generateAsync({ type: 'blob' }), extension: 'zip', name: 'split-pages' } } throw new Error('This tool needs a processing backend') }
const backendTools = new Set(['JPG to PDF', 'Merge PDF', 'Split PDF', 'Remove pages', 'Extract pages', 'Rotate PDF', 'Repair PDF', 'Compress PDF', 'Organize PDF', 'Add page numbers', 'Add watermark', 'Crop PDF', 'PDF Forms', 'Compare PDF', 'PDF to Markdown'])
const convertWithBackend = async (toolName: string, files: File[]) => { if (!backendTools.has(toolName) || toolName === 'JPG to PDF' || location.hostname.endsWith('github.io')) return null; const form = new FormData(); form.append('tool', toolName); files.forEach((file) => form.append('files', file, file.name)); let response: Response; try { response = await fetch('/api/convert', { method: 'POST', body: form }) } catch { return null } if (response.status === 404) return null; if (!response.ok) { const body = await response.json().catch(() => ({})); throw new Error(body.error || 'The backend could not process this file.') } const disposition = response.headers.get('content-disposition') || ''; const filename = disposition.match(/filename="?([^";]+)"?/)?.[1] || `${toolName.toLowerCase().replaceAll(' ', '-')}.pdf`; const extension = filename.split('.').pop() || 'pdf'; return { blob: await response.blob(), extension, name: filename.replace(/\.[^/.]+$/, '') } }
const renderModalFiles = () => { modalFiles.innerHTML = selectedFiles.map((file, index) => `<div class="file-row"><span class="file-type">${file.name.split('.').pop()?.toUpperCase() || 'FILE'}</span><span class="file-details"><strong>${file.name}</strong><small>${formatBytes(file.size)}</small></span><button class="remove-file" data-file-index="${index}" aria-label="Remove ${file.name}">×</button></div>`).join(''); convertButton.disabled = selectedFiles.length === 0; conversionStatus.textContent = selectedFiles.length ? `${selectedFiles.length} file${selectedFiles.length > 1 ? 's' : ''} ready to process.` : '' }
const resetConversion = () => { conversionRun += 1; if (conversionTimer) window.clearInterval(conversionTimer); if (outputUrl) URL.revokeObjectURL(outputUrl); outputUrl = ''; progressArea.hidden = true; downloadButton.hidden = true; progressBar.style.width = '0%'; progressValue.textContent = '0%'; progressLabel.textContent = 'Preparing files'; convertButton.disabled = selectedFiles.length === 0; conversionStatus.textContent = '' }
const openTool = (name: string) => { selectedTool = tools.find((item) => item.name === name) ?? tools[0]; document.querySelector('#modal-title')!.textContent = selectedTool.name; document.querySelector('#modal-description')!.textContent = selectedTool.description; document.querySelector('#modal-icon')!.textContent = selectedTool.icon; document.querySelector('#modal-icon')!.className = `modal-icon ${selectedTool.color}`; modalFileInput.accept = selectedTool.name === 'JPG to PDF' ? 'image/jpeg,image/png,.jpg,.jpeg,.png' : browserPdfTools.has(selectedTool.name) || browserImageTools.has(selectedTool.name) || backendTools.has(selectedTool.name) ? 'application/pdf,.pdf' : 'application/pdf,image/*,.doc,.docx,.xls,.xlsx,.ppt,.pptx'; selectedFiles = []; modalFileInput.value = ''; resetConversion(); renderModalFiles(); modal.hidden = false }
document.addEventListener('click', (event) => { const target = event.target as HTMLElement; const tool = target.closest<HTMLElement>('[data-tool]'); if (tool) openTool(tool.dataset.tool!); if (target.matches('.modal-close') || target === modal) { resetConversion(); modal.hidden = true } })
document.querySelector('#search')?.addEventListener('input', (event) => { query = (event.target as HTMLInputElement).value; renderTools() })
document.querySelectorAll<HTMLButtonElement>('.category-tab').forEach((button) => button.addEventListener('click', () => { activeCategory = button.dataset.category!; document.querySelectorAll('.category-tab').forEach((tab) => tab.classList.remove('selected')); button.classList.add('selected'); renderTools() }))
document.querySelectorAll<HTMLAnchorElement>('.floating-nav-item').forEach((item) => item.addEventListener('click', () => { document.querySelectorAll('.floating-nav-item').forEach((navItem) => navItem.classList.remove('active')); item.classList.add('active') }))
const dropzone = document.querySelector<HTMLLabelElement>('#dropzone')!
const fileInput = document.querySelector<HTMLInputElement>('#file-input')!
const showFiles = (files: FileList | null) => { if (files?.length) { dropzone.classList.add('has-files'); dropzone.querySelector('strong')!.textContent = `${files.length} file${files.length > 1 ? 's' : ''} selected`; dropzone.querySelector('span:not(.upload-icon)')!.textContent = 'Ready to choose a tool' } }
fileInput.addEventListener('change', () => showFiles(fileInput.files)); dropzone.addEventListener('dragover', (event) => { event.preventDefault(); dropzone.classList.add('dragging') }); dropzone.addEventListener('dragleave', () => dropzone.classList.remove('dragging')); dropzone.addEventListener('drop', (event) => { event.preventDefault(); dropzone.classList.remove('dragging'); showFiles(event.dataTransfer?.files ?? null) })
modalFileInput.addEventListener('change', () => { if (modalFileInput.files?.length) { selectedFiles = [...modalFileInput.files]; resetConversion(); renderModalFiles() } })
modalFiles.addEventListener('click', (event) => { const button = (event.target as HTMLElement).closest<HTMLButtonElement>('[data-file-index]'); if (button) { resetConversion(); selectedFiles.splice(Number(button.dataset.fileIndex), 1); renderModalFiles() } })
convertButton.addEventListener('click', async () => { if (!selectedFiles.length) return; if (!browserSupportedTools.has(selectedTool.name) && !browserPdfTools.has(selectedTool.name) && !browserImageTools.has(selectedTool.name) && !backendTools.has(selectedTool.name)) { conversionStatus.textContent = 'This tool needs an external processing engine before it can create a valid output.'; return } if (selectedFiles.some((file) => file.size > 100 * 1024 * 1024)) { conversionStatus.textContent = 'Please choose files smaller than 100 MB.'; return } if ((browserPdfTools.has(selectedTool.name) || browserImageTools.has(selectedTool.name) || backendTools.has(selectedTool.name)) && selectedTool.name !== 'JPG to PDF' && selectedFiles.some((file) => file.type !== 'application/pdf')) { conversionStatus.textContent = 'Please choose PDF files for this tool.'; return } if (selectedTool.name === 'JPG to PDF' && selectedFiles.some((file) => !file.type.startsWith('image/'))) { conversionStatus.textContent = 'Please choose image files for this tool.'; return } resetConversion(); const currentRun = conversionRun; convertButton.disabled = true; progressArea.hidden = false; downloadButton.hidden = true; progressLabel.textContent = 'Converting your file'; let progress = 0; conversionTimer = window.setInterval(() => { progress = Math.min(progress + 5, 95); progressBar.style.width = `${progress}%`; progressValue.textContent = `${progress}%` }, 120); try { const result = await convertWithBackend(selectedTool.name, selectedFiles) ?? await createPdfOutput(selectedTool.name, selectedFiles); if (currentRun !== conversionRun) return; if (conversionTimer) window.clearInterval(conversionTimer); outputUrl = URL.createObjectURL(result.blob); progressBar.style.width = '100%'; progressValue.textContent = '100%'; progressLabel.textContent = 'Conversion ready'; conversionStatus.textContent = `Valid ${result.extension.toUpperCase()} created${backendTools.has(selectedTool.name) && !location.hostname.endsWith('github.io') ? ' by the PDFflex API' : ' in your browser'}.`; downloadButton.dataset.extension = result.extension; downloadButton.dataset.outputName = result.name; downloadButton.hidden = false } catch (error) { if (currentRun !== conversionRun) return; if (conversionTimer) window.clearInterval(conversionTimer); progressBar.style.width = '0%'; progressValue.textContent = '0%'; progressLabel.textContent = 'Conversion failed'; conversionStatus.textContent = error instanceof Error ? error.message : 'This operation could not be completed.'; convertButton.disabled = false } })
downloadButton.addEventListener('click', () => { if (!outputUrl || !selectedFiles[0]) return; const baseName = selectedFiles[0].name.replace(/\.[^/.]+$/, ''); const extension = downloadButton.dataset.extension || 'pdf'; const suffix = downloadButton.dataset.outputName || 'converted'; const link = document.createElement('a'); link.href = outputUrl; link.download = `${baseName}-${suffix}.${extension}`; document.body.appendChild(link); link.click(); link.remove() })
